#ifndef MOBILEDEVICE_GLOBAL_H
#define MOBILEDEVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MOBILEDEVICE_LIBRARY)
#  define MOBILEDEVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define MOBILEDEVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MOBILEDEVICE_GLOBAL_H
